version: "3"
services:
  api-database:
    image: mongo
    container_name: "api-database"
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
    networks:
      - spring-mongo-net
  api:
    build: .
    image: api-docker-image
    ports:
      - 9091:8080
    depends_on:
      - api-database
    links:
      - api-database
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge


